title: Sweet And Savory Sourdough
description: Small-batch sourdough loaves and treats baked fresh in Superior, Wisconsin.

# MUST MATCH YOUR REPO NAME (including capitalization)
baseurl: "/SweetAndSavorySourdough"

# Your GitHub username
url: "https://adamholden7.github.io"

theme: null
markdown: kramdown
plugins: []
